name: .NET
on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      shell: pwsh
      run: ./build.ps1
      env:
        TAG: ${{ github.ref_name }}
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./Build/*.zip
        body: "[Change log](https://github.com/AndrewSav/Memento?tab=readme-ov-file#change-log)"
